// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
			int n = Integer.parseInt(args[0]);
				int counter1 = 0 , counter2 = 0;
				int t = n;
				while(t > 0){
					double random = Math.random() * n;
					if(random > 0.5){
						counter1++;
					} else{
						counter2++;
					}
					t--;
				}
				if(counter2 != 0 && counter1 != 0){
					double ratio = counter1 / counter2;
					System.out.println("> 0.5: " + counter1 + " times");
					System.out.println("<= 0.5: " + counter2 + " times");
					System.out.println("Ratio: " + ratio);
				}else{
					System.out.println("> 0.5: " + counter1 + " times");
					System.out.println("<= 0.5: " + counter2 + " times");
				}
			
	}
}
